---
title: "M2 Colinear Test"
output: html_document
date: "2025-03-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(here)
library(ggplot2)
library(car)

```

```{r}
m2_colinear <- read.csv(here("data", "new_clean_data", "data", "all_vars_colinear.csv"))

```

```{r}
## remove NA values ##

m2_colinear <- na.omit(m2_colinear)

```

```{r}
## create correlation matrix 

m2_colinear_numeric <- m2_colinear %>% 
  select(-market, -content_type) 

cor_matrix <- cor(m2_colinear_numeric, use = "complete.obs")
print(cor_matrix)

```

```{r}
## print out those with correlation greater than 0.7 ##

cor_tidy <- cor_matrix %>%
  as.data.frame() %>%
  rownames_to_column(var = "Variable1") %>%
  pivot_longer(-Variable1, names_to = "Variable2", values_to = "Correlation") %>%
  filter(Variable1 != Variable2) %>%  
  filter(abs(Correlation) > 0.7) %>%  
  arrange(desc(abs(Correlation))) 

print(cor_tidy)


```

```{r} 
## create fake DV and test VIF 

m2_colinear_numeric$dummy_dependent <- rnorm(nrow(m2_colinear_numeric))  


model <- lm(dummy_dependent ~ ., data = m2_colinear_numeric %>% select(-dummy_dependent, everything()))


vif_values <- vif(model)

vif_tidy <- data.frame(
  Variable = names(vif_values),
  VIF = vif_values
) %>%
  arrange(desc(VIF))

print(vif_tidy)
